spring:
  application:
    name: auction-zone-backend
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  cache:
    type: none

  server:
    port: 8080

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
              - openid
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 3600000   # 1 hour
  jwtIssuer: "auctionzone"

cors:
  allowedOrigins: ${CORS_ORIGIN}
  allowedMethods: ${CORS_METHODS}
  allowedHeaders: "*"
  allowCredentials: true

logging:
  level:
    com.auctionzone: DEBUG
    org.springframework.security: DEBUG






